// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FftChart: typeof import('./views/FftChart.vue')['default']
    Halp: typeof import('./views/halp.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    'Home copy': typeof import('./views/Home copy.vue')['default']
    IconsIconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    PricePredictions: typeof import('./views/PricePredictions.vue')['default']
    RandomWalk: typeof import('./views/RandomWalk.vue')['default']
    Sine: typeof import('./views/Sine.vue')['default']
    SineWave: typeof import('./views/SineWave.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    Uplot: typeof import('uplot-vue')['default']
    UplotVue: typeof import('uplot-vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}

export { }
